var autoTitle = {
    "Chanthaly": null,
    "Dark Touch": null,
    "The Darkness": null,
    "Cradle of Fear": null,
    "Bloodsuckers": null,
    "Manhattan Baby": null,
    "Shadow": null,
    "Pontypool": null,
    "The Mummy's Shroud": null,
    "Zombie Night": null,
    "Rampo Noir": null,
    "Dead Rising: Watchtower": null,
    "Hellions": null,
    "Thir13en Ghosts": null,
    "The St. Francisville Experiment": null,
    "Phantom of the Opera": null,
    "Tony": null,
    "See No Evil 2": null,
    "Amityville Terror": null,
    "Poltergeist": null,
    "Kotsutsubo": null,
    "Lemora: A Child's Tale of the Supernatural": null,
    "The Mummy Resurrected": null,
    "Always Watching: A Marble Hornets Story": null,
    "Orca": null,
    "Cry of the Banshee": null,
    "Amityville: It's About Time": null,
    "The Triangle": null,
    "It's Alive III: Island of the Alive": null,
    "A Christmas Horror Story": null,
    "The Haunted": null,
    "Zombie Holocaust": null,
    "sxtape": null,
    "Dahshat": null,
    "The Horde": null,
    "The Blood Spattered Bride": null,
    "Wolf Creek": null,
    "Jeepers Creepers": null,
    "House of Bones": null,
    "Bone Tomahawk": null,
    "Final Exam": null,
    "Sweet Home": null,
    "The Kiss of the Vampire": null,
    "Apartment 1303 3D": null,
    "Search for the Beast": null,
    "The Impossible Convicts": null,
    "It's My Mother's Birthday Today": null,
    "Portrait Werner Herzog": null,
    "Inauguration of the Pleasure Dome": null,
    "Break Free": null,
    "Gregory Go Boom": null,
    "Hunger": null,
    "Light Is Calling": null,
    "Oil: A Symphony in Motion": null,
    "42 One Dream Rush": null,
    "La cartomancienne": null,
    "Balance": null,
    "The Code": null,
    "Fugu & Tako": null,
    "Encounter in the Third Dimension": null,
    "Dottie Gets Spanked": null,
    "Patton Oswalt: No Reason to Complain": null,
    "The Hearts of Age": null,
    "Sevilla -> (Infinity) 06": null,
    "24 heures de la vie d'un clown": null,
    "The Heart of the World": null,
    "Monkeyshines, No. 2": null,
    "In Order Not to Be Here": null,
    "We Were Once a Fairytale": null,
    "Orderly or Disorderly": null,
    "Blablabl\u00e1": null,
    "Puce Moment": null,
    "Curb Dance": null,
    "The Bogus Man": null,
    "In Youth, Beside the Lonely Sea": null,
    "I Am Syd Stone": null,
    "The Best of Ernie and Bert": null,
    "Sallie Gardner at a Gallop": null,
    "An Introduction to Physics": null,
    "The Key to Reserva": null,
    "Return to Reason": null,
    "La cravate": null,
    "Entr'acte": null,
    "Hole": null,
    "The 3 Rs": null,
    "Space Battleship Yamato": null,
    "Fei du juan yun shan": null,
    "The Giant of Marathon": null,
    "Baji": null,
    "Commando": null,
    "Sasori": null,
    "Lahore": null,
    "Sharktopus vs. Whalewolf": null,
    "Forbidden City Cop": null,
    "Redline": null,
    "Fists of Legend": null,
    "Assassin X": null,
    "Star Trek": null,
    "Recoil": null,
    "American Samurai": null,
    "Act of Valor": null,
    "Kickboxer: Vengeance": null,
    "Fist of Legend": null,
    "Shestoy": null,
    "Einstein": null,
    "Big and Little Wong Tin Bar": null,
    "Die Fighting": null,
    "The Heat": null,
    "Shaolin vs. Lama": null,
    "Fatal Contact": null,
    "Howard the Duck": null,
    "Ichi": null,
    "T.N.T.": null,
    "Outside the Law": null,
    "Blood Out": null,
    "The Shaolin Temple": null,
    "Za jia xiao zi": null,
    "Legacy": null,
    "American Justice": null,
    "Blast": null,
    "Kamikaze Taxi": null,
    "Ong-bak": null,
    "Aadhavan": null,
    "The Soldier": null,
    "Belly of the Beast": null,
    "The Defender": null,
    "Fight Back to School": null,
    "Tekken: Kazuya's Revenge": null,
    "You Carry Me": null,
    "Sword of Vengeance": null,
    "Bounty Hunters": null,
    "Blades of Blood": null,
    "The Peacekeeper": null,
    "Den demokratiske terroristen": null,
    "Army Dog": null,
    "Flaming Star": null,
    "'49-'17": null,
    "Firecreek": null,
    "Unforgiven": null,
    "Devil's Doorway": null,
    "Apache Rifles": null,
    "High Plains Drifter": null,
    "For a Few Dollars More": null,
    "The Tall T": null,
    "The Gunfight at Dodge City": null,
    "Into the Badlands": null,
    "Bad Girls": null,
    "Wild Heritage": null,
    "The Duel at Silver Creek": null,
    "Two Rode Together": null,
    "A Big Hand for the Little Lady": null,
    "Vengeance": null,
    "Yellowstone Kelly": null,
    "The Man Behind the Gun": null,
    "Pecos River": null,
    "Man with the Gun": null,
    "Gunfighters": null,
    "Lo chiamavano King": null,
    "Face of a Fugitive": null,
    "Death Rides a Horse": null,
    "One-Eyed Jacks": null,
    "Rustlers' Rhapsody": null,
    "The Animals": null,
    "Prairie Fever": null,
    "The Outlaw Josey Wales": null,
    "Beyond the Law": null,
    "God Forgives... I Don't!": null,
    "Ride in the Whirlwind": null,
    "Lawman": null,
    "The Daughter of Dawn": null,
    "Hombre": null,
    "The War Wagon": null,
    "Tension at Table Rock": null,
    "Catlow": null,
    "Ride Beyond Vengeance": null,
    "Adios Compa\u00f1eros": null,
    "Seven Dollars on the Red": null,
    "Adios Sabata": null,
    "Aces and Eights": null,
    "The Magnificent Seven Ride!": null,
    "Night Passage": null,
    "Countdown": null,
    "The War in Space": null,
    "Coneheads": null,
    "Robot Sound": null,
    "Flash Gordon's Trip to Mars": null,
    "Nos amis les Terriens": null,
    "Flash Gordon": null,
    "Return of the Ghostbusters": null,
    "War Wolves": null,
    "Golem": null,
    "Il pianeta degli uomini spenti": null,
    "Ready Player One": null,
    "Rocketship X-M": null,
    "Project Moon Base": null,
    "Ghost from the Machine": null,
    "Without Warning": null,
    "Alien Nation: The Enemy Within": null,
    "Alien Escape": null,
    "Das Arche Noah Prinzip": null,
    "Deceit": null,
    "Invasion of the Saucer Men": null,
    "Mars Needs Women": null,
    "The Galaxy Invader": null,
    "10,000 Days": null,
    "Sol": null,
    "Alien Nation: The Udara Legacy": null,
    "Alien Nation: Body and Soul": null,
    "Beginning of the End": null,
    "The Mind of Mr. Soames": null,
    "984: Prisoner of the Future": null,
    "Robot Monster": null,
    "Operation Ganymed": null,
    "Assignment: Outer Space": null,
    "The Space Children": null,
    "Liquid Sky": null,
    "The Creation of the Humanoids": null,
    "Clonehunter": null,
    "Warning from Space": null,
    "Tornado Warning": null,
    "The Hitch Hikers Guide to the Galaxy": null,
    "Battle in Outer Space": null,
    "Future War": null,
    "Idaho Transfer": null,
    "Lunopolis": null,
    "Armageddon": null,
    "Suspect Zero": null,
    "Almost Blue": null,
    "Drum": null,
    "Snow in Paradise": null,
    "Born to Raise Hell": null,
    "Teenage Bank Heist": null,
    "Keyhole": null,
    "Cannibal": null,
    "The Gray Man": null,
    "Skinheads": null,
    "Lord of Darkness": null,
    "Dead Silent": null,
    "The Mercury Conspiracy": null,
    "The Flower with the Deadly Sting": null,
    "Stranger in My House": null,
    "Icon": null,
    "The Cheerleader Murders": null,
    "Dead Calm": null,
    "Diva": null,
    "The Girl on the Train": null,
    "Vic + Flo Saw a Bear": null,
    "The Bride He Bought Online": null,
    "Not Safe for Work": null,
    "Defense of the Realm": null,
    "The King's Surrender": null,
    "Dhund: The Fog": null,
    "The Kidnapping of the President": null,
    "Enter the Dangerous Mind": null,
    "Freeway": null,
    "The Breach": null,
    "The Man Who Haunted Himself": null,
    "Headhunter": null,
    "Fear X": null,
    "Traders": null,
    "The Guvnors": null,
    "Rajathandhiram": null,
    "The Subjects": null,
    "Sugar Daddies": null,
    "planet": null,
    "alien": null,
    "future": null,
    "spaceship": null,
    "aliens": null,
    "space": null,
    "cardigan": null,
    "humans": null,
    "moon": null,
    "people": null,
    "jake": null,
    "giant": null,
    "futuristic": null,
    "astronauts": null,
    "crash": null,
    "mars": null,
    "like": null,
    "built": null,
    "film": null,
    "short": null,
    "edison": null,
    "routine": null,
    "minute": null,
    "look": null,
    "dances": null,
    "filmmaker": null,
    "educational": null,
    "picture": null,
    "thomas": null,
    "kanye": null,
    "featuring": null,
    "woman": null,
    "camera": null,
    "accordion": null,
    "heads": null,
    "earth": null,
    "team": null,
    "drug": null,
    "agent": null,
    "brother": null,
    "cop": null,
    "terrorists": null,
    "kung": null,
    "shaolin": null,
    "treasure": null,
    "fighting": null,
    "kidnapped": null,
    "killers": null,
    "japanese": null,
    "fu": null,
    "china": null,
    "avenge": null,
    "gang": null,
    "sheriff": null,
    "cattle": null,
    "indian": null,
    "gold": null,
    "western": null,
    "outlaw": null,
    "marshal": null,
    "outlaws": null,
    "ranch": null,
    "men": null,
    "war": null,
    "cowboys": null,
    "brothers": null,
    "bounty": null,
    "civil": null,
    "gunslinger": null,
    "army": null,
    "cowboy": null,
    "house": null,
    "young": null,
    "horror": null,
    "group": null,
    "dead": null,
    "castle": null,
    "vampire": null,
    "friends": null,
    "haunted": null,
    "night": null,
    "town": null,
    "revenge": null,
    "dr": null,
    "terrifying": null,
    "zombies": null,
    "home": null,
    "killer": null,
    "man": null,
    "thriller": null,
    "girl": null,
    "family": null,
    "murder": null,
    "car": null,
    "old": null,
    "life": null,
    "takes": null,
    "couple": null,
    "secret": null,
    "terrorist": null,
    "london": null,
    "mysterious": null,
    "gets": null,
    "deadly": null
};